<a href="https://colab.research.google.com/github/linghduoduo/Deep-Learning/blob/master/Transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install transformers

     |████████████████████████████████| 1.8MB 12.7MB/s 
     |████████████████████████████████| 2.9MB 50.3MB/s 
     |████████████████████████████████| 890kB 56.0MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893261 sha256=1daca8e4da5c11e1d9c7a1da44694da89ab4253a8c79da641c0bebf557d5c5f1
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [2]:
from transformers import pipeline

In [3]:
classifier = pipeline('sentiment-analysis')

In [4]:
classifier('We are very happy to include pipeline into the transformers repository.')

[{'label': 'POSITIVE', 'score': 0.9978193640708923}]

In [5]:
question_answerer = pipeline('question-answering')

In [6]:
question_answerer({
...     'question': 'What is the name of the repository ?',
...     'context': 'Pipeline have been included in the huggingface/transformers repository'
... })

{'answer': 'huggingface/transformers',
 'end': 59,
 'score': 0.5135958790779114,
 'start': 35}

In [7]:
from transformers import AutoTokenizer, AutoModel

In [8]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

In [9]:
model = AutoModel.from_pretrained("bert-base-uncased")

In [10]:
inputs = tokenizer("Hello world!", return_tensors="pt")

In [11]:
outputs = model(**inputs)

In [12]:
inputs

{'input_ids': tensor([[ 101, 7592, 2088,  999,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1]])}

In [13]:
outputs

BaseModelOutputWithPoolingAndCrossAttentions([('last_hidden_state',
                                               tensor([[[-0.1424,  0.1335, -0.1291,  ..., -0.3597, -0.0562,  0.3605],
                                                        [-0.3506,  0.1042,  0.6244,  ..., -0.1761,  0.4834,  0.0644],
                                                        [-0.2451, -0.1573,  0.6945,  ..., -0.5654, -0.0894, -0.1856],
                                                        [-0.8248, -0.9119, -0.6561,  ...,  0.5074, -0.1939, -0.1659],
                                                        [ 0.8767,  0.0352, -0.1233,  ...,  0.2720, -0.6369, -0.1585]]],
                                                      grad_fn=<NativeLayerNormBackward>)),
                                              ('pooler_output',
                                               tensor([[-8.9756e-01, -3.3040e-01, -7.6942e-01,  7.5799e-01,  4.6678e-01,
                                                        -1.2035e

In [14]:
from transformers import AutoTokenizer, TFAutoModel

In [15]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

In [16]:
model = TFAutoModel.from_pretrained("bert-base-uncased")

Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [17]:
inputs = tokenizer("Hello world!", return_tensors="tf")

In [18]:
outputs = model(**inputs)

In [19]:
inputs

{'input_ids': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[ 101, 7592, 2088,  999,  102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[1, 1, 1, 1, 1]], dtype=int32)>}

In [20]:
outputs

TFBaseModelOutputWithPooling([('last_hidden_state',
                               <tf.Tensor: shape=(1, 5, 768), dtype=float32, numpy=
                               array([[[-0.14241171,  0.13353686, -0.12907067, ..., -0.35967964,
                                        -0.05622256,  0.36050177],
                                       [-0.3506475 ,  0.10419714,  0.6244457 , ..., -0.1761034 ,
                                         0.48340183,  0.06443473],
                                       [-0.2451309 , -0.15731743,  0.69451946, ..., -0.5654469 ,
                                        -0.08940041, -0.18564405],
                                       [-0.8247858 , -0.9119232 , -0.65607107, ...,  0.5074244 ,
                                        -0.19388784, -0.16587651],
                                       [ 0.8766518 ,  0.0352484 , -0.12331423, ...,  0.272016  ,
                                        -0.63689995, -0.15850073]]], dtype=float32)>),
                        